### PR TITLE
Add support to persist cookies for multiple calls

### PR DESCRIPTION
**Pull request by JanBerktold**
Use checker.SetPersistCookies(bool) to set whether cookies should be saved. Default is set to clear cache between cookies in order to maintain backwards compatibility.

Any feedback? :)

### CODE REVIEW

**Comment by ivpusic** [comment]
hmm...with this tests are somehow dependent. You rely on something from test before. Tests should be independent. I think we should not allow users to do this. If you have a few tests it is simple to follow, but if you have many tests it can be a mess.

**Comment by JanBerktold** [comment]
While you have a point, it may be useful for situations where you need to "login" to some kind of API and then perform actions following that authorization, since session information is kept in cookies.

For example:

``` go
func TestSomething(t *testing.T) {
    checker := httpcheck.New(t, &testHandler{}, ":3000")
    checker.SetPersistCookies(true)

    // sucessfull login
    checker.Test("POST", "/login").
        WithHeader("user", "blabla").
        WithHeader("pass", "secret123").
        Check().
        HasStatus(200)

    // fetch some info
    checker.Test("GET", "/get_super_secret_info").
        Check().
        HasJson(&someType{})
}
```

Also: Would you be fine with me creating an additional pull request with methods to include content into the request's body or did you exclude those on purpose?

**Comment by ivpusic** [comment]
It would be great if you could create something like `WithBody([]byte)`.

I like your usecase for `SetPersistCookies`. But I think we should not enable this for all cookies, but only for explicitly defined. In this case we will see clearly if something is persisted between tests or not.

So I propose something like:
`checker.PersistCookie(string)` where argument is key of cookie to persist.

**Comment by JanBerktold** [comment]
Changed API to:

```
checker.PersistCookie(cookie string)
checker.UnpersistCookie(cookie string)
```

**Comment by ivpusic** [comment]
Can you just improve `TestCookies` to check that some "cookieX" which is not persisted, is not available in next test?

**Comment by JanBerktold** [comment]
[TestCookiesDelete](https://github.com/JanBerktold/httpcheck/blob/master/httpcheck_test.go#L284) should already be doing that or am I missing something?

**Comment by JanBerktold** [comment]
Also, what about `WithJSONBody`, `WithXMLBody`, as well as the convenience wrappers `WithBodyString` and `HasBodyString`?

**Comment by ivpusic** [comment]
I thought about adding something like (this is just quick copy/paste, didn't try it, but here is an idea):

```
func TestCookies(t *testing.T) {
    mockT := new(testing.T)
    checker := makeTestChecker(mockT)
    checker.PersistCookie("some")

    checker.Test("GET", "/some")
    checker.Check()

    checker.HasCookie("some", "cookie")
    checker.HasCookie("someCookieWhichIsNotPersisted", "cookie")
    assert.False(t, mockT.Failed())

    checker.Test("GET", "/nothing")
    checker.Check()

       // check if cookie exists (it should not, because we didn't call ``PersistCookie`` for this cookie)
    checker.HasCookie("someCookieWhichIsNotPersisted", "cookie")
    assert.True(t, mockT.Failed())

    checker.HasCookie("some", "cookie")
    assert.False(t, mockT.Failed())
}
```

**Comment by ivpusic** [comment]
Adding `WithJsonBody`, `WithXmlBody`, `HasBodyString`, etc. would be awesome. I didn't have much time when I was writing this lib, so this is missing currently.

Just please test as much as possible that methods are working.

**Comment by JanBerktold** [comment]
All right, added that into `TestCookies` and removed `TestCookiesDelete`. Also moved it to the handler `/cookies` so it does not interfere with other tests. Mind merging this request? Will create a new branch for the other methods.

**Pull request merged**
